# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeefbd026f9aa28133e114ac0d98153d450c00c904642a9e5aa86bf48c9bb075c6c394ce09555058a1c9fed0285d8b9cee340dcb6fd5c0c9644e53d0aa03bce3

test:
  secret_key_base: c3f228627c8761e5723c7d35a35d6ad20aedaecb3a9095d5c9fcb5c0918ca1485f77f3d68faea3e1137d26282ef0571df6da4f368e77a76b8907563fdf095447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
